### PR TITLE
change plyvel version to 1.0.5 to support ubuntu 18.04 / python3.6

### PR DESCRIPTION
**Pull request by osthafen**

### CODE REVIEW

**Comment by gdassori** [comment]
How the current plyvel version inhibit the usage with ubuntu 18.04 \ python 3.6 ?
Please check issue #58

**Comment by osthafen** [comment]
It seems like the plyvel wheels for ubuntu 18.04 python exist since Version 1.0.5:
wbolster/plyvel#78

**Comment by gdassori** [comment]
Hi,

The problem is not with the availability of the latest plyvel version on
newer systems, but on olds.

May I ask you why the 1.0.5?
Spruned works well with the 0.9.x, and has a zero-effort compatibility also
on an old raspbian, for instance.

Thnx!

Il mer 5 set 2018, 17:07 osthafen <notifications@github.com> ha scritto:

**Comment by gdassori** [comment]
Withdrawn, I guess.

**Pull request closed without merging**
